### PR TITLE
Initial packaging for Debian

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by adrelanos** [comment]
Not sure if I can make that work. Going to need some support sorting out build issues such as:

https://github.com/ResistancePlatform/resistance-miner/issues/7

**Comment by solardiz** [comment]
I've just commented on #7, but I don't see how a custom Makefile could possibly result in a successful build when your system doesn't have the curl development library installed.

**Comment by solardiz** [comment]
Can _all_ of the files introduced here perhaps be under `debian/`?

Is `changelog.upstream` needed at all? It will tend to become out of date, and we already have `NEWS`, which is more meaningful for users.

Is `man/minerd.1.ronn` needed at all? We already have a real `minerd.1` man page at top level.

**Comment by adrelanos** [comment]
Solar Designer:
> I've just commented on #7, but I don't see how a custom Makefile could possibly result in a successful build when your system doesn't have the curl development library installed.
> 


Separate thing, unrelated. Makefile isn't supposed (and wasn't tested)
in #7.

**Comment by adrelanos** [comment]
All change requests done.
Updated version of https://github.com/Whonix/genmkfile required.

    /usr/share/genmkfile/make-helper.bsh deb-pkg
    /usr/share/genmkfile/make-helper.bsh deb-install

**Comment by solardiz** [comment]
Thanks. I don't mind merging this now, although I also see no benefit in merging this work-in-progress. Should we merge?

**Comment by solardiz** [comment]
I also find it weird that our Debian package would depend on Whonix-derived(?) genmkfile.

**Comment by adrelanos** [comment]
Solar Designer:
> Thanks. I don't mind merging this now, although I also see no benefit in merging this work-in-progress. Should we merge?
> 


Not work in progress. Good enough for speedy package creation as per
slack. Please merge.

**Comment by adrelanos** [comment]
Solar Designer:
> I also find it weird that our Debian package would depend on Whonix-derived(?) genmkfile.


genmkfile while developed by Whonix, is a non-Whonix specific, generic tool.

Certainly avoidable and able to re-invent its functionality without use
genmkfile but more effort for unknown gain.

**Pull request merged**
